name: chat
description: A new Flutter application.

version: 1.1.01

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  flutter_spinkit: ^4.1.2
  firebase_messaging: ^7.0.3
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  firebase_analytics: ^5.0.2
  wiredash: ^0.4.0
  image_picker: ^0.6.7+21
  focused_menu: ^1.0.2
  image_downloader: ^0.20.1
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo_notext.png
